---

version: "3.1"

services:
  cloudserver-data:
    image: scality/s3server
    ports:
      - "9991"
    networks:
      - backend
    environment:
      S3DATAPATH: /data
      LISTEN_ADDR: 0.0.0.0
    volumes:
      - "cloudserver-data:/data:rw"
    command: npm run start_dataserver
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.labels.io.zenko.type == storage

  cloudserver-metadata:
    image: scality/s3server
    ports:
      - "9990"
    networks:
      - backend
    environment:
      S3METADATAPATH: /metadata
      LISTEN_ADDR: 0.0.0.0
    volumes:
      - 'cloudserver-metadata:/metadata:rw'
    command: npm run start_mdserver
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.labels.io.zenko.type == storage

  cloudserver-front:
    image: scality/s3server
    ports:
      - "8000"
    networks:
      - backend
      - frontend-dmz
    environment:
      DATA_HOST: cloudserver-data
      METADATA_HOST: cloudserver-metadata
      REDIS_HOST: cache
      ENDPOINT: "${ENDPOINT:-zenko}"
    secrets:
      - cloudserver-credentials
    command: npm run start_s3server
    depends_on:
      - cloudserver-data
      - cloudserver-metadata
      - cache
    deploy:
      mode: replicated
      update_config:
        parallelism: 1
        delay: "10s"
        monitor: "5s"

  cache:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - backend

  lb:
    image: zenko/loadbalancer
    ports:
      - "80:80"
    environment:
      LISTEN_PORT: 80
      UPSTREAM_SERVER: "cloudserver-front:8000"
    networks:
      - frontend
      - frontend-dmz
    depends_on:
      - cloudserver-front
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: "10s"
        monitor: "5s"

  zookeeper:
    image: zookeeper
    ports:
      - "2181"
    networks:
      - backend
    volumes:
      - "backbeat-data:/data:rw"
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.labels.io.zenko.type == storage

  kafka:
    image: zenko/kafka
    ports:
      - "9092"
    networks:
      - backend
    volumes:
      - "backbeat-data:/data:rw"
    depends_on:
      - zookeeper
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.labels.io.zenko.type == storage

  backbeat:
    image: zenko/backbeat
    networks:
      - backend
    command: npm start
    depends_on:
      - kafka
      - cloudserver-front
    deploy:
      mode: replicated


networks:
  backend:
  frontend:
  frontend-dmz:

volumes:
  cloudserver-data:
  cloudserver-metadata:
  backbeat-data:

secrets:
  cloudserver-credentials:
    file: ./secrets.txt
